#
# Basic example
#


#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -9.81

timeStep: 0.01
start_pybullet_after_initialization: true
status_hz: 50


#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 1.0
  cameraYaw: -45
  cameraPitch: -45.0
  cameraTargetPosition: [-0.6, 0.0, 0.3]


#
# Pybullet objects
#
visual_objects:
  - "{ros_quat_ds}/configs/interpolation/visual_wpt1.yaml"
  - "{ros_quat_ds}/configs/interpolation/visual_wpt2.yaml"
  - "{ros_quat_ds}/configs/interpolation/visual_wpt3.yaml"
collision_objects:
  - "{ros_quat_ds}/configs/floor.yaml"
robots:
  # - "{rpbi_examples}/configs/interpolation/kuka_lwr.yaml"
  - "{ros_quat_ds}/configs/interpolation/franka.yaml"

